### ISSUE TITLE
NukeTesting as standalone package

### ISSUE THREAD

**Issue by gillesvink** [cglukas/NukeTesting#11]
It would be good to have the NukeTesting as a standalone package, that would be able to invoke the correct Nuke interpreter, or even better, import Nuke into the current interpreter:
https://learn.foundry.com/nuke/developers/15.0/pythondevguide/nuke_as_python_module.html

This way, the end user would not have to care about dependancies, as they are all already defined in the requirements for this pacakge.

**Comment by cglukas** [comment]
I really like this idea. It would be great to just install this project and run it out of the box.

It would also make it very easy for others to use it. 

We should decide on a packaging tool that we want to use. Do you have any favourites yet? 

In my mind I have two particular use cases: 
- importing the package in an already existing testing environment (like at our previous employee)
- running `nuke-testing` from the command line (like `pylint` or `ruff`) for users without a testing environment. Arguments would point to the test files/folders and a `config` option could make it possible to override the used nuke installation. 

The second option is more difficult as we need to find the nuke installation that matches the python version. 

Speaking of version compatibility: we could theoretically support any python version but it would make more sense to only support nuke compliant versions. Thereby we reduce the risks of incompatibility between the python interpreter and the nuke package.

**Comment by gillesvink** [comment]
Sounds good!

I think probably setuptools would be a good option for us, as it's the most widely used packaging tool.

I agree on the two use-cases:

1. Launch python interpreter to create a subprocess of Nuke interactive to run test script
2. Run with our own python instance and import Nuke there.

For this I think we could have one simple entry-point: the nuke-testrunner command. This will decide if it should launch a new subprocess or if it should import Nuke and run it that way.

In anyway, it would require to find an existing Nuke installation for both options.

This could be defined in a argument, or a config as you mentioned.


An example command could be this one:
nuke-testrunner --nuke_dir /path/to/nuke --test_dir /path/to/test/dir

Or to run with a Nuke subprocess:
nuke-testrunner --nuke_dir /path/to/nuke --run_interactive --test_dir /path/to/test/dir

Or to run with defined config:
nuke-testrunner --config nuke_testrunner.json

Or auto run if it would find a nuke_testrunner.json file in the current directory:
nuke-testrunner

Of course, it would also accept any pytest args to give the same flexibility.


What do you think?

**Comment by cglukas** [comment]
Sounds good. And also quite complex already 😅.
A config system is already implemented. And the commandline runner too.
Only the forwarding of pytest args and the pure python run are not
implemented.

I think it would be good to create a 'cli' package to manage our
commandline interface in one place.
This should only be available for internal use while the nuke test tools
are available for import.

Gilles Vink ***@***.***> schrieb am Sa., 13. Juli 2024, 11:01:

**Comment by gillesvink** [comment]
Absolutely, I agree
