### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by gillesvink** [cglukas/NukeTesting#22]
We should add a repo license like MIT (or another if preferred).

**Comment by cglukas** [comment]
Sure 👍 I'm fine with something that allows for commercial use but no re-selling. So that studios can use the package. I just don't want ppl to sell our code. Very unlikely tbh 🤣

**Comment by gillesvink** [comment]
> Sure 👍 I'm fine with something that allows for commercial use but no re-selling. So that studios can use the package. I just don't want ppl to sell our code. Very unlikely tbh 🤣 

I think the Mozilla Public License (MPL) might be good for us. Wdyt?

https://opensource.stackexchange.com/questions/8831/pros-and-cons-of-using-mpl-2-0-license

**Comment by cglukas** [comment]
LGTM we should add this one
