### ISSUE TITLE
Automate repo code checking and tests

### ISSUE THREAD

**Issue by gillesvink** [cglukas/NukeTesting#8]
To make sure all code is working, we should automate our tests to be run before merging.
This will prevent any non-working tests to be present on the main branch.
The tests will report the coverage.

Also there should be pre-commit checks to validate all pep rules.

**Comment by cglukas** [comment]
Thats quite nice for our pure python tests but how are we running nuke related tests?
Is there a way of getting a dev license for a testrunner?

**Comment by gillesvink** [comment]
Unfortunately I don't think we can run Nuke here. One option would be though to have a selfhosted runner that is linked, but that would require a license that is able to run in a docker environment.

Besides that, I think a lot can still be tested though, with some patching

**Comment by cglukas** [comment]
Yeah, we probably need to add a pytest mark for Nuke only tests.
